// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppConfiguration", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Doctor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Appointments_AppointmentId_Unique");

                    b.HasIndex("PatientProfileId")
                        .HasDatabaseName("IX_Appointments_PatientProfileId");

                    b.HasIndex("VisitEnd")
                        .HasDatabaseName("IX_Appointments_VisitEnd");

                    b.HasIndex("VisitStart")
                        .HasDatabaseName("IX_Appointments_VisitStart");

                    b.HasIndex("PatientProfileId", "VisitStart")
                        .HasDatabaseName("IX_Appointments_PatientId_VisitStart");

                    b.ToTable("Appointments", null, t =>
                        {
                            t.HasComment("Записи на прием к врачу");
                        });
                });

            modelBuilder.Entity("Core.Entities.AppointmentSearchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DoctorIds")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DoctorNames")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSearchAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LpuName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDaysToSearch")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<long>("SearchInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SpecificStartPoints")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimePreferencesPresetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ViewOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AppointmentSearchRequests_CreatedAt");

                    b.HasIndex("PatientProfileId")
                        .HasDatabaseName("IX_AppointmentSearchRequests_PatientProfileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AppointmentSearchRequests_Status");

                    b.HasIndex("DoctorIds", "LpuName")
                        .HasDatabaseName("IX_AppointmentSearchRequests_Doctor_Lpu");

                    b.HasIndex("Status", "LastSearchAttempt")
                        .HasDatabaseName("IX_AppointmentSearchRequests_Status_LastSearchAttempt");

                    b.ToTable("AppointmentSearchRequests", (string)null);

                    b.HasDiscriminator<string>("RequestType").HasValue("AppointmentSearchRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LpuAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LpuId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LpuShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PatientBirthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientMiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PatientProfiles_PatientId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PatientProfiles_UserId");

                    b.HasIndex("UserId", "PatientId")
                        .IsUnique()
                        .HasDatabaseName("IX_PatientProfiles_UserId_PatientId_Unique");

                    b.ToTable("PatientProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PatientProfiles_Birthdate", "\"PatientBirthdate\" <= CURRENT_DATE");

                            t.HasCheckConstraint("CK_PatientProfiles_Email_Format", "\"RecipientEmail\" IS NULL OR \"RecipientEmail\" LIKE '%@%.%'");
                        });
                });

            modelBuilder.Entity("Core.Entities.TimePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExcludedDates")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDaysAhead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHoursFromNow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("PreferredTimeFrom")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("PreferredTimeTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("IX_TimePreferences_UserId_Name");

                    b.ToTable("TimePreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimePreferences_TimeRange", "(\"PreferredTimeFrom\" IS NULL AND \"PreferredTimeTo\" IS NULL) OR \r\n              (\"PreferredTimeFrom\" IS NOT NULL AND \"PreferredTimeTo\" IS NOT NULL AND \r\n               \"PreferredTimeFrom\" < \"PreferredTimeTo\")");
                        });

                    b.HasDiscriminator<string>("TimeMode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Username_Length", "LENGTH(\"username\") >= 3");
                        });
                });

            modelBuilder.Entity("Core.Entities.ManualSearchRequest", b =>
                {
                    b.HasBaseType("Core.Entities.AppointmentSearchRequest");

                    b.HasDiscriminator().HasValue("Manual");
                });

            modelBuilder.Entity("Core.Entities.ReferralSearchRequest", b =>
                {
                    b.HasBaseType("Core.Entities.AppointmentSearchRequest");

                    b.Property<string>("ReferralNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("ReferralNumber");

                    b.HasDiscriminator().HasValue("Referral");
                });

            modelBuilder.Entity("Core.Entities.AnyTimePreference", b =>
                {
                    b.HasBaseType("Core.Entities.TimePreference");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TimePreferences_TimeRange", "(\"PreferredTimeFrom\" IS NULL AND \"PreferredTimeTo\" IS NULL) OR \r\n              (\"PreferredTimeFrom\" IS NOT NULL AND \"PreferredTimeTo\" IS NOT NULL AND \r\n               \"PreferredTimeFrom\" < \"PreferredTimeTo\")");
                        });

                    b.HasDiscriminator().HasValue("AnyTime");
                });

            modelBuilder.Entity("Core.Entities.MonthDayPreference", b =>
                {
                    b.HasBaseType("Core.Entities.TimePreference");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TimePreferences_TimeRange", "(\"PreferredTimeFrom\" IS NULL AND \"PreferredTimeTo\" IS NULL) OR \r\n              (\"PreferredTimeFrom\" IS NOT NULL AND \"PreferredTimeTo\" IS NOT NULL AND \r\n               \"PreferredTimeFrom\" < \"PreferredTimeTo\")");
                        });

                    b.HasDiscriminator().HasValue("SpecificDates");
                });

            modelBuilder.Entity("Core.Entities.WeekDayPreference", b =>
                {
                    b.HasBaseType("Core.Entities.TimePreference");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TimePreferences_TimeRange", "(\"PreferredTimeFrom\" IS NULL AND \"PreferredTimeTo\" IS NULL) OR \r\n              (\"PreferredTimeFrom\" IS NOT NULL AND \"PreferredTimeTo\" IS NOT NULL AND \r\n               \"PreferredTimeFrom\" < \"PreferredTimeTo\")");
                        });

                    b.HasDiscriminator().HasValue("WeekdayPattern");
                });

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.HasOne("Core.Entities.PatientProfile", "PatientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("Core.Entities.AppointmentSearchRequest", b =>
                {
                    b.HasOne("Core.Entities.PatientProfile", "PatientProfile")
                        .WithMany("AppointmentSearchRequests")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("Core.Entities.PatientProfile", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.TimePreference", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("TimePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.PatientProfile", b =>
                {
                    b.Navigation("AppointmentSearchRequests");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("TimePreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
