<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsNukeBuildProject>true</IsNukeBuildProject>
    <RootNamespace>Build</RootNamespace>
    <NukeTelemetryVersion>1</NukeTelemetryVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="Nuke.Common" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
</Project>
