services:
    server:
        image: gorzdravbooking-server:local
        build:
            context: ..
            dockerfile: src/Presentation/Server/Dockerfile
        ports:
            - "5023:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        volumes:
            - gorzdrav-data:/data

volumes:
    gorzdrav-data:

